version: "3.6"
services:
  express:
    build:
      context: ./express
      dockerfile: DockerfileProd
    volumes:
      - ./express:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "postgres"
    environment:
      TOKEN_KEY: ${JWT_SECRET_KEY}
      PG_PASSWORD: ${POSTGRES_PW}

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}

  hasura:
    image: hasura/graphql-engine:v2.0.9.cli-migrations-v3
    depends_on:
      - "postgres"
      - "express"
    restart: always
    working_dir: /hasura
    volumes:
      - ./hasura:/hasura
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PW}@postgres:5432/postgres
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PW}@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PW}@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      ## HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_SEEDS_DIR: /hasura/seeds
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key": "${JWT_SECRET_KEY}"}'

  vue:
    build:
      context: ./vue
      dockerfile: DockerfileProd
    volumes:
      - /usr/src/app/node_modules
      - vue_static:/usr/src/app/dist
    environment:
      VITE_APP_HASURA_HTTP_URL: ${HASURA_HTTP_URL}
      VITE_APP_HASURA_WS_URL: ${HASURA_WS_URL}
      HASURA_SECRET: ${HASURA_SECRET}

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - vue_static:/srv
    depends_on:
      - "vue"
      - "hasura"
volumes:
  db_data:
  caddy_data:
    external: true
  caddy_config:
  vue_static:
