SET check_function_bodies = false;
INSERT INTO auth.users (id, first_name, last_name, email, encrypted_password) VALUES (1, 'Alex', 'Harrison', 'alexmon32@live.com', '$2b$10$JOqotauKtihMFiIkzJfz.ud7D8pJofe.rQtckCzFLFFtUhaKQDX2K');
INSERT INTO public.experiment_type (id, description) VALUES ('other', 'Other');
INSERT INTO public.experiment_type (id, description) VALUES ('orbital', 'Oribital');
INSERT INTO public.experiment_type (id, description) VALUES ('surface', 'Surface');
INSERT INTO public."group" (id, created_at, updated_at, title, description) VALUES (1, '2021-10-02 22:26:21.384749+00', '2021-10-02 22:26:21.384749+00', 'Admin', 'administrates');
INSERT INTO public.group_xref_users (id, created_at, updated_at, group_id, user_id) VALUES (1, '2021-10-02 22:28:15.189797+00', '2021-10-02 22:28:15.189797+00', 1, 1);
SELECT pg_catalog.setval('auth.users_id_seq', 1, true);
SELECT pg_catalog.setval('public.equipment_id_seq', 1, false);
SELECT pg_catalog.setval('public.experiments_id_seq', 1, false);
SELECT pg_catalog.setval('public.group_id_seq', 1, true);
SELECT pg_catalog.setval('public.group_xref_users_id_seq', 1, true);
SELECT pg_catalog.setval('public.meta_field_id_seq', 1, false);
SELECT pg_catalog.setval('public.meta_key_id_seq', 1, false);
SELECT pg_catalog.setval('public.mission_elements_components_functions_id_seq', 1, false);
SELECT pg_catalog.setval('public.mission_elements_id_seq', 1, false);
SELECT pg_catalog.setval('public.mission_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_id_seq', 1, false);
SELECT pg_catalog.setval('public.post_tags_id_seq', 1, false);
SELECT pg_catalog.setval('public.sensitive_post_id_seq', 1, false);
SELECT pg_catalog.setval('public.tag_category_id_seq', 1, false);
SELECT pg_catalog.setval('public.tag_id_seq', 1, false);
